### ISSUE TITLE
How to use ClientEventMocker

### ISSUE THREAD

**Issue by larsekje** [Strand94/progarkprosjekt#29]
**Attempted procedure**
1. Run ClientEventMocker
2. Run application
3. Enter 'start-game' event

**Expected result**
Communicator should call startGame() in ClientController. If it does this, a message will be printed to the terminal.

**Actual result**
ClientEventMocker prints `Event 'start-game' emitted`, but nothing happens in the application.

**Comment by ivarkrabol** [comment]
The class is intended to emit events to the server (by the client, which is why i thought of them as client events - I see how that could be confusing), as if the client sent them. I don't think we've made a similar feature to mock events sent by the server to the client.
