### ISSUE TITLE
Rewind

### ISSUE THREAD

**Issue by michoy** [Strand94/progarkprosjekt#33]
**Plan for hvordan det skal fungere:** 
Når spillet avsluttes, sendes et array med _notepads_ fra _Game_ til hver av clientene. _clientController_ tar av seg visingen av disse til spilleren. _LobbyMasteren_ får opp en ekstra knapp og velger når neste bilde/gjett skal vises.

**TODOs**

- _clientController_ må vite om spilleren er _lobbyMaster_. Kanskje enklest å løse dette med å lagre infoen i _Player_ objektet? 

- Nye events må settes opp for å håndtere når neste bilde/gjett skal vises. Foreslår noe som _start-rewind_ , _rewind-show-next_ og _rewind-finished_ 

i gameController:

- dersom _endGame_ eller _abortGame_ kalles => emit _start-rewind_ med notpadene som for øyeblikket er i _Game_

**Comment by michoy** [comment]
# Transfer of notepad between server and client

**images will be sent to server as base64 strings**

---

**Step 1** test already existing jsonTonotepadList (which uses gson lib)

**Step 2** if step 1 doesn't work, try serialization using json.org, which socket.io also uses

**Comment by michoy** [comment]
**what's left now:** 

- write logic for rewind in clientController

- write views for rewind

**Comment by larsekje** [comment]
- LobbyMaster should be able to request that the server broadcasts `onRewindShowNext ` to all players.
