### ISSUE TITLE
Server side models required by Client

### ISSUE THREAD

**Issue by larsekje** [Strand94/progarkprosjekt#4]
Some models are required by the client (Sheet, Guess, Drawing, Notepad), but according to [class_diagram_1.0.jpg](https://drive.google.com/file/d/1c2668IMFB0t6ZEXwncWnmJxvQPYahZyj/view?usp=sharing) they reside on server. Currently they are in Models.Should_this_even_be_here_qm. 

Solution: Import from Server when server skeleton is in place

**Comment by ivarkrabol** [comment]
If we go for the node.js/socket.io approach (which I think we are), then all the server-side code will be in javascript. So basically the models that cross over will have to be written twice, once in java and once in js.
