### ISSUE TITLE
Drawing objective is not displayed

### ISSUE THREAD

**Issue by ivarkrabol** [Strand94/progarkprosjekt#47]

**Comment by larsekje** [comment]
Seems to be a server related. 
 `notepad.getLastSheet().getObjectiveWord()` at [here](https://github.com/Strand94/Sketchy/blob/ebcb80b5aa4bd4fbd7c9d5e05ab67469d87e1015/client-side/core/src/com/sketchy/game/communicator/Communicator.java#L162) returns `null`.

Maybe @ivarkrabol can look into this?
